### ISSUE TITLE
crash when scale and save

### ISSUE THREAD

**Issue by ghost** [arenatemp/sd-tagging-helper#15]
Description:
Image: scale / png
Prompt: none
-> crash

Traceback (most recent call last):
  File "C:\Users\nobody\Desktop\sd-tagging-helper-master\helper.py", line 333, in run
    self.img.writeScale(img_file, self.dim)
  File "C:\Users\nobody\Desktop\sd-tagging-helper-master\helper.py", line 486, in writeScale
    s = dim/min(w, h)
UnboundLocalError: local variable 'w' referenced before assignment

**Comment by arenasys** [comment]
fixed by bc2c5feafdac305cf64ac4121e409b72f501aa38
